export {
  closeDatabase,
  databasePaths,
  openDatabaseForInit,
  openExistingDatabaseForServe,
  removeFreshDatabaseFiles,
  verifyPragmaPolicy,
  withImmediateTransaction,
  type DatabaseOpenDependencies,
  type DatabasePaths,
  type OpenDatabaseResult,
  type SqliteDatabase,
  type SqliteDatabaseOpener,
  type SqlitePragmaPolicy,
  type SynchronousTransactionCallback,
} from './db.js';
export {
  discoverMigrations,
  KNOWN_MIGRATION_VERSIONS,
  readMigrationLedger,
  runMigrations,
  validateAppliedPrefix,
  type Migration,
  type MigrationLedger,
  type MigrationRunOptions,
  type MigrationRunResult,
} from './migrations.js';
export {
  verifyDatabaseIntegrity,
  EXPECTED_INDEXES,
  EXPECTED_INDEXES_BY_VERSION,
  EXPECTED_TABLES,
  EXPECTED_TRIGGERS,
  EXPECTED_TRIGGERS_BY_VERSION,
  type IntegrityReport,
} from './integrity.js';
export {
  CANONICAL_SCHEMA_DEFINITIONS,
  CANONICAL_SCHEMA_DEFINITIONS_BY_VERSION,
  canonicalSchemaDefinitionsForVersion,
  canonicalizeSchemaSql,
  fingerprintSchemaSql,
  type CanonicalSchemaDefinitions,
  type CanonicalSchemaVersion,
} from './schemaDefinitions.js';
export {
  createStructuralRepositories,
  type ActorRepository,
  type ActorRow,
  type ActorTokenRepository,
  type ActorTokenRow,
  type AuthoritativeStatusRow,
  type DecisionGrantRow,
  type ReferenceRepository,
  type StructuralRepositories,
} from './repositories.js';
